## Name and class of the tagger
tagger: 
  var: fj_x_ParticleNetMD_XccVsQCD  ## fj_x is a placeholder of fj_1 & fj_2
  type: cc  ## cc or bb
  working_points:
    name: pnV02
    range: {HP: [0.99, 1.], MP: [0.96, 0.99], LP: [0.90, 0.96]}

## Jet pT ranges for fit
pt_range:
  name: pt250w100
  range: [[250, 350], [350, 450], [450, 100000]]

## Sample configuration
samples:
  year: 2018
  sample_prefix: samples/trees_sf/20210102_pnV02_ak15_qcd
