## ====================================================================================================
## Routine name
routine_name: 20210331_bb_vbfhh4b

year: 2018

## Type of the tagger, can be 'cc' or 'bb'
type: bb

## Sample configuration
samples:
  ## Name used as an identifier for storing backup files
  name: 20210324_bb

  ## Prefix of the main samples produced from NanoHRT
  # 'sample_prefix' follows the name format as produced by NanoHRT-tools (see README)
  sample_prefix: samples/trees_sf/particlenet_ak8_20210113_ak8_qcd
  
  # if or not using the additional b-enriched input
  use_bflav: False

## Name and class of the tagger
tagger:
  ## The variable name of the tagger (use fj_x as a placeholder of fj_1 & fj_2)
  var: fj_x_ParticleNetMD_XbbVsQCD

  # Working points of the tagger for calibration ('name' and keys of 'range' used only as identifiers)
  working_points:
    name: pnV02bb
    range: {HP: [0.98, 1.], MP: [0.94, 0.98], LP: [0.90, 0.94]}

## Jet pT ranges for fit ('name' used as an identifier)
pt_range:
  name: pt400w100
  range: [[400, 500], [500, 600], [600, 800], [800, 100000]]

## ====================================================================================================
## Additional config needed in preprocessing step 3-2: the signal X->cc (or X->bb) tree and the 
## selections used in the main analysis ('name' used as an identifier)
main_analysis_tree:
  name: vbfhhto4b_base

  ## The sample path: can be relative or absolute path. $YEAR is a placeholder of year in format e.g. 2018;
  ## treename: the name of the tree to read in the file
  path: samples/trees/20210224_v4trees_$YEAR_vbf/LHEWeight/vbfhhto4b-cv_1-c2v_0-c3_1-recoiloff_tree.root
  treename: Events

  ## The selection used for this sample in the main analysis. This is how we enable that the g->cc 
  ## (or g->bb) jets serve as a reasonable proxy to the signal jets under the phase-space defined below
  ## *NOTE*: should always use parentheses between & and |
  selection: (n_ak8>=2) & (ak8_1_pt>500) & (ak8_2_pt>400) & (ak8_1_regressed_mass>50) & (ak8_1_regressed_mass<200) & (ak8_2_regressed_mass>50) & (ak8_2_regressed_mass<200)
  
  ## Name of the same tagger defined in this tree
  tagger: ak8_2_ParticleNetMD_HbbVsQCD
  
  ## Name of jet pT var defined in this tree
  pt_var: ak8_2_pt

  ## Event weight expression
  weight: genWeight*xsecWeight*puWeight
  
  ## Signal label to make the signal/proxy plots
  label: 'VBF HH(4b) subl jet'

  ## (Optional) additional variables only used in step 3-5
  addition_var:
    mass: ak8_2_regressed_mass
    tau21: 